google-ai-edge/LiteRT

.github/workflows/release_pypi_macos.yml

There was a build error "clang: error: unknown argument: '-mavxvnniint8'" when building latest TF codes on macos-13.
https://github.com/google-ai-edge/LiteRT/actions/runs/11015482791/job/30588762709
We will re-enable macos-13 build once we fix this error later.

Disable pypi nightly build on macos-13 due to build error

---

litert/test/testdata/simple_broadcast_to_op_boolean.mlir
litert/test/testdata/simple_broadcast_to_op_fp32.mlir
litert/vendors/qualcomm/compiler/BUILD
litert/vendors/qualcomm/compiler/qnn_compose_graph.cc
litert/vendors/qualcomm/core/builders/BUILD
litert/vendors/qualcomm/core/builders/broadcast_to_op_builder.cc
litert/vendors/qualcomm/core/builders/broadcast_to_op_builder.h

Summary:
- Enable op builder for broadcast to op
- Add 2 mlir model for different data type

Qualcomm AI Engine Direct - Enable BroadcastTo OP

---

litert/vendors/qualcomm/core/common.h
litert/vendors/qualcomm/core/utils/log.h
litert/vendors/qualcomm/core/utils/log_android.cc
litert/vendors/qualcomm/core/utils/log_default.cc
litert/vendors/qualcomm/core/utils/utils_test.cc
litert/vendors/qualcomm/dispatch/BUILD
litert/vendors/qualcomm/dispatch/litert_dispatch_invocation_context.cc
litert/vendors/qualcomm/dispatch/litert_dispatch_invocation_context.h
litert/vendors/qualcomm/qnn_manager.cc
litert/vendors/qualcomm/qnn_manager.h

Summary:
- Use kProfilingOff profiling_level as default for now
- Implement QNN profiler with simple format
- Can be tested with dispatch_api_qualcomm_test
- Need to add into dispatch option after header interface merged

Qualcomm AI Engine Direct - Enable QNN profiler in LiteRt

---

litert/vendors/qualcomm/core/builders/pad_op_builder.cc

Summary:
- Apply a workaround using a magic number to fix the accuracy of padv2

Qualcomm AI Engine Direct - Fix PadV2 accuracy

---

litert/vendors/qualcomm/core/builders/op_builder.cc

Summary:
- Fix the calculation function for padding used in MaxPool2D
The attributes of MaxPool2D here are:
| Property                    | Value |
|-----------------------------|-------|
| **filter_height**           | 3 : i32 |
| **filter_width**            | 3 : i32 |
| **padding**                 | VALID |
| **stride_h**                | 2 : i32 |
| **stride_w**                | 2 : i32 |
| **fused_activation_function** | NONE |

Qualcomm AI Engine Direct - Fix MaxPool2D in ResNet50

---

litert/vendors/qualcomm/compiler/qnn_compiler_plugin.cc
litert/vendors/qualcomm/compiler/qnn_compose_graph.cc
litert/vendors/qualcomm/qnn_manager.cc

Summary:
- Bypass RMSNorm for validation
- Disable int16ToUint16 feature
- Leave TODO to remove later

Qualcomm AI Engine Direct - Bypass int16 and RMSNorm

---

litert/c/litert_model.cc
litert/c/litert_model.h
litert/c/litert_model_test.cc
litert/cc/litert_model.h
litert/cc/litert_model_test.cc
litert/core/model/model.h
litert/core/model/model_graph.cc
litert/core/model/model_graph_test.cc
litert/core/model/model_load.cc

Add `tensor_index` to `LiteRtTensor` which matches the index shows in model_explorer. 
Required by future vendor feature and provide better debug experience.
```
//litert/cc:litert_model_test
[==========] 21 tests from 8 test suites ran. (1 ms total)
[  PASSED  ] 21 tests.
//litert/c:litert_model_test
[==========] 23 tests from 6 test suites ran. (0 ms total)
[  PASSED  ] 23 tests.
//litert/core/model:model_graph_test
[==========] 22 tests from 3 test suites ran. (0 ms total)
[  PASSED  ] 22 tests.
//litert/vendors/qualcomm/compiler/qnn_compiler_plugin_test
[==========] 174 tests from 5 test suites ran. …
```

Qualcomm AI Engine Direct - Add LiteRt Tensor Index

---

litert/vendors/mediatek/compiler/legalizations/legalize_helper.h
litert/vendors/mediatek/compiler/legalizations/transpose_conv_op_legalization.cc

1. Fix the incorrect padding for `conv2d `& `depthwiseConv2d `& `transposeConv`

[NeuroPilot] Fix incorrect parameters for legalize

---

litert/tools/BUILD
litert/tools/run_model.cc

1. Support the iteration argument to execute the graph multiple times.
2. Record the run time and calculate the statistics.
3. Use ABSL_LOG and remove LITERT_LOG.
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1689520440.064678   15029 run_model.cc:150] Model: /data/local/tmp/weilhuan/torchvision_efficientnet_b0_compiled.tflite
...
VERBOSE: Replacing 1 out of 1 node(s) with delegate (DispatchDelegate) node, yielding 1 partitions for subgraph 0.
INFO: [litert/vendors/qualcomm/context_binary_info.cc:110] Found qnn graph: qnn_partition_0
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
I0000 00:00:1689520440.503551   15029 run_model.cc:179] Signature index: 0
I0000 00:00:1689520440.503730   15029 run_model.cc:181] Prepare input …
```

Qualcomm AI Engine Direct - run_model support the iteration argument.

---

litert/vendors/qualcomm/compiler/qnn_compiler_plugin_test.cc
litert/vendors/qualcomm/core/schema/soc_table.cc
litert/vendors/qualcomm/core/schema/soc_table.h

`qnn_compiler_plugin_test`
```[----------] Global test environment tear-down
[==========] 175 tests from 5 test suites ran. (12814 ms total)
[  PASSED  ] 175 tests.```

Qualcomm AI Engine Direct - Support V69 Devices

---

litert/vendors/mediatek/compiler/compiler_plugin.cc
litert/vendors/mediatek/compiler/create_model.cc
litert/vendors/mediatek/compiler/create_model.h
litert/vendors/mediatek/compiler/legalizations/BUILD
litert/vendors/mediatek/compiler/legalizations/extra_data_mgr.h
litert/vendors/mediatek/compiler/legalizations/fully_connected_op_legalization.cc
litert/vendors/mediatek/compiler/legalizations/neuron_utils.cc
litert/vendors/mediatek/compiler/legalizations/neuron_utils.h
litert/vendors/mediatek/compiler/legalizations/operand_map.cc
litert/vendors/mediatek/compiler/legalizations/operand_map.h
litert/vendors/mediatek/compiler/legalizations/transpose_conv_op_legalization.cc

- Support new data types: int4 & int64 Notice that we currently force cast int64 to int32
- Introduce an extra data manager to manage additional tensor data
- Add new legalizations for Padv2 and Dequantize

[NeuroPilot] Support Int4/Int64 for legalizations

---

litert/vendors/qualcomm/compiler/qnn_compose_graph.cc
litert/vendors/qualcomm/core/wrappers/tensor_wrapper.cc
litert/vendors/qualcomm/core/wrappers/tensor_wrapper.h

Summary:
- Update bias QNN quant params in ConvertAxisScaleOffsetToScaleOffset().
- Integrate the use of std::visit for QNN tensor quantization parameters within UpdateQnnQuantParams().
- Set unknown dimension from -1 to 1.
`qint8_Conv2d_DepthConv2d.tflite` can be fully delegated.
Target //litert/vendors/qualcomm/core/transformation:graph_to_graph_test
```
[==========] 2 tests from 1 test suite ran. (0 ms total)
[  PASSED  ] 2 tests.
```
Target //litert/vendors/qualcomm/compiler:qnn_compiler_plugin_test
```
[==========] 172 tests from 4 test suites ran. (19524 ms total)
[  PASSED  ] 172 tests.
```
Target //litert/vendors/qualcomm/dispatch:_dispatch_api_qualcomm_test
```
[----------] Global test …
```

Qualcomm AI Engine Direct - Correct bias quant params for Conv2D.

---

litert/vendors/qualcomm/core/BUILD
litert/vendors/qualcomm/core/common_test.cc

Add test for qualcomm option class
`bazel-bin/litert/vendors/qualcomm/core/common_test`
```
```

Qualcomm AI Engine Direct - Qualcomm Option Tests

---

litert/vendors/mediatek/compiler/compiler_plugin.cc
litert/vendors/mediatek/compiler/legalizations/legalize_helper.h
litert/vendors/mediatek/compiler/legalizations/operand_map.cc
litert/vendors/mediatek/compiler/legalizations/operand_map.h

1. allocate extra memory for the zero bias to prevent the data from being released before call compilation.

[NeuroPilot] Fix fully-connected bias issue

---

litert/vendors/qualcomm/dispatch/litert_dispatch_device_context.cc

Summary:
- Change to rank 1 and dimension [1] for 0-dimensional tensors.

Qualcomm AI Engine Direct - Address the registration issue of 0-dimensional tensors in dispatch.

---

litert/vendors/qualcomm/core/wrappers/op_wrapper.cc

Summary:
- Add .get() for reference_wrapper in UpdateTensors.

Qualcomm AI Engine Direct - Fix JIT QC build error.

---

litert/vendors/qualcomm/compiler/qnn_compiler_plugin.cc
litert/vendors/qualcomm/core/transformation/BUILD
litert/vendors/qualcomm/core/transformation/graph_to_graph.cc
litert/vendors/qualcomm/core/transformation/graph_to_graph_test.cc
litert/vendors/qualcomm/core/transformation/mask.cc
litert/vendors/qualcomm/core/transformation/mask.h

- QNN does not support Quant Op with float32 inputs and int16 outputs
- Transform [logic not] -> [cast] -> [quant] -> [mul] into a [e-wise select].
```
======================== Test Summary ========================
[==========] 12 tests from 3 test suites ran. (0 ms total)
[  PASSED  ] 12 tests. …
```

Qualcomm AI Engine Direct - Transform Quantize Op in Gemma3 Mask

---

litert/vendors/qualcomm/compiler/qnn_compose_graph.cc

```
[==========] 12 tests from 3 test suites ran. (0 ms total)
[  PASSED  ] 12 tests.
//litert/vendors/qualcomm/core/wrappers/tests:param_wrapper_test
[==========] 16 tests from 2 test suites ran. (0 ms total) …
```

Qualcomm AI Engine Direct - Fix Conv2D Options.

---

litert/vendors/qualcomm/core/builders/broadcast_to_op_builder.cc

[==========] 12 tests from 3 test suites ran. (4 ms total)
[  PASSED  ] 12 tests.
//litert/vendors/qualcomm/core/wrappers/tests:param_wrapper_test
[==========] 16 tests from 2 test suites ran. (0 ms total) …

Qualcomm AI Engine Direct - Support INT32 Broadcast_to.

---

litert/vendors/qualcomm/qnn_manager.cc

Summary:
- 16bit RMSNorm validation supported on QNN 2.35, remove the workaround.

Qualcomm AI Engine Direct - Remove workaround for RMSNorm validation.

---

litert/vendors/qualcomm/core/builders/gathernd_op_builder.cc

Summary:
- Static indice has been supported on QNN 2.35, remove the workaround.

Qualcomm AI Engine Direct - Remove workaround for GatherNd.

---

litert/vendors/qualcomm/BUILD
litert/vendors/qualcomm/qnn_manager.cc

- Align QNN library version check with QNN TFLiteDelegate
```
[==========] 12 tests from 3 test suites ran. (0 ms total)
[  PASSED  ] 12 tests.
//litert/vendors/qualcomm/core/wrappers/tests:param_wrapper_test
[==========] 16 tests from 2 test suites ran. (0 ms total)
[ …
```

Qualcomm AI Engine Direct - Refine QNN Library Version Check.

---

litert/vendors/qualcomm/compiler/qnn_compose_graph.cc
litert/vendors/qualcomm/core/builders/op_builder.cc
litert/vendors/qualcomm/core/builders/op_builder.h

- Original method modifies the Op output tensor, will impact future feature development
- Change to create a new tensor but not modify the output tensor vector
```
[==========] 11 tests from 3 test suites ran. (1 ms total)
[  PASSED  ] 11 tests.
//litert/vendors/qualcomm/core/wrappers/tests:param_wrapper_test …
```

Qualcomm AI Engine Direct - Refactor Fuse Activation.

---

litert/vendors/qualcomm/core/builders/BUILD
litert/vendors/qualcomm/core/builders/fully_connected_op_builder.cc

1. int64 bias is not supported in QNN, convert it to int32 to pass op validation.
2. Assume the value of bias won't exceed the range of int32.
- op validation pass for the FC ops in new Gemma3n 2b.

Qualcomm AI Engine Direct - Convert FC bias from int64 to int32
